# Generated by Django 6.1.1 on 2026-09-29 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(choices=[('Drama', 'Drama'), ('Romance', 'Romance'), ('Comedy', 'Comedy'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Action', 'Action'), ('Family', 'Family'), ('Crime', 'Crime'), ('Other', 'Other')], default='Drama', max_length=50)),
                ('script_type', models.CharField(choices=[('Short Film', 'Short Film'), ('Feature Film', 'Feature Film'), ('Web Series', 'Web Series'), ('YouTube', 'YouTube'), ('Drama', 'Drama'), ('Advertisement', 'Advertisement'), ('Other', 'Other')], default='Short Film', max_length=50)),
                ('author_name', models.CharField(blank=True, max_length=150)),
                ('language', models.CharField(default='Malayalam', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_number', models.PositiveIntegerField(default=1)),
                ('heading', models.CharField(default='INT. LOCATION - DAY', max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='scripts.script')),
            ],
            options={
                'ordering': ['order', 'scene_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary'), ('Other', 'Other'), ('Not Specified', 'Not Specified')], default='Not Specified', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='scripts.script')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScriptElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('scene_heading', 'Scene Heading'), ('action', 'Action'), ('character', 'Character'), ('dialogue', 'Dialogue'), ('parenthetical', 'Parenthetical'), ('transition', 'Transition'), ('shot', 'Shot'), ('note', 'Note')], default='action', max_length=30)),
                ('content', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='scripts.scene')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScriptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Plot Ideas', 'Plot Ideas'), ('Character Ideas', 'Character Ideas'), ('Research', 'Research'), ('Dialogue Ideas', 'Dialogue Ideas'), ('Things to Change', 'Things to Change'), ('General', 'General')], default='General', max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='scripts.script')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(default='Draft Snapshot', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('snapshot_data', models.JSONField(help_text='Full JSON snapshot of scenes and elements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='scripts.script')),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['user', '-updated_at'], name='scripts_scr_user_id_b3a8a7_idx'),
        ),
        migrations.AddIndex(
            model_name='scene',
            index=models.Index(fields=['script', 'order'], name='scripts_sce_script__b43650_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('script', 'name')},
        ),
        migrations.AddIndex(
            model_name='scriptelement',
            index=models.Index(fields=['scene', 'order'], name='scripts_scr_scene_i_a9b55d_idx'),
        ),
    ]
