# Generated by Django 6.1.1 on 2026-09-30 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='parent_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_scenes', to='scripts.scene'),
        ),
        migrations.AddIndex(
            model_name='scene',
            index=models.Index(fields=['parent_scene', 'order'], name='scripts_sce_parent__baaaa7_idx'),
        ),
    ]
