# Generated by Django 6.1.1 on 2026-10-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_scene_parent_scene_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='duplicate_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
