# Generated by Django 6.1.1 on 2026-10-02 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_scene_duplicate_number_scene_is_duplicate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptTitlePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Custom title on title/cover page if different from screenplay title.', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle, tagline, or genre specification.', max_length=255)),
                ('author_name', models.CharField(blank=True, help_text='Primary author/screenwriter name.', max_length=150)),
                ('pen_name', models.CharField(blank=True, help_text='Optional pen name or pseudonym.', max_length=150)),
                ('adaptation_credits', models.TextField(blank=True, help_text='Optional adaptation, story by, or source material credits.')),
                ('copyright_registration', models.TextField(blank=True, help_text='Optional registration or copyright notice (free text, e.g. FEFKA / WGA registration, copyright statement).')),
                ('draft_revision', models.CharField(blank=True, help_text='Draft revision label (e.g. First Draft, Revision 2, Shooting Draft).', max_length=100)),
                ('draft_date', models.CharField(blank=True, help_text='Draft date (e.g. October 2026 or 2026-10-02).', max_length=100)),
                ('contact_name', models.CharField(blank=True, help_text='Contact person name (screenwriter, agent, or representative).', max_length=150)),
                ('contact_email', models.CharField(blank=True, help_text='Contact email address.', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='title_page', to='scripts.script')),
            ],
            options={
                'verbose_name': 'Script Title Page',
                'verbose_name_plural': 'Script Title Pages',
            },
        ),
    ]
