# Generated by Django 6.1.1 on 2026-10-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_scripttitlepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripttitlepage',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email address.', max_length=254),
        ),
    ]
