# Generated by Django 6.1.1 on 2026-10-04 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_alter_scripttitlepage_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='intercut_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercut_instances', to='scripts.scene'),
        ),
        migrations.AddField(
            model_name='scene',
            name='is_intercut',
            field=models.BooleanField(default=False),
        ),
    ]
