# Generated by Django 6.1.1 on 2026-10-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_scene_intercut_source_scene_is_intercut'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='transition',
            field=models.CharField(blank=True, default='CUT TO:', max_length=100),
        ),
    ]
