# Generated by Django 6.1.1 on 2026-10-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0007_scene_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='transition',
            field=models.CharField(blank=True, default='CUT TO', max_length=100),
        ),
    ]
