# Generated by Django 6.1.1 on 2026-10-05 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0008_alter_scene_transition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptBackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_date', models.DateField(help_text='The calendar date of this daily backup.')),
                ('backup_type', models.CharField(choices=[('EMAIL', 'Email Backup'), ('GDRIVE', 'Google Drive Backup')], default='EMAIL', max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='SUCCESS', max_length=20)),
                ('recipient_email', models.CharField(blank=True, help_text='Destination email address for EMAIL backup.', max_length=254)),
                ('filename', models.CharField(blank=True, help_text='Filename of the generated PDF backup.', max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='Size of the generated PDF in bytes.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if the backup failed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_logs', to='scripts.script')),
            ],
            options={
                'verbose_name': 'Script Backup Log',
                'verbose_name_plural': 'Script Backup Logs',
                'ordering': ['-backup_date', '-created_at'],
                'indexes': [models.Index(fields=['backup_date', 'status'], name='scripts_scr_backup__78315b_idx'), models.Index(fields=['script', 'backup_date', 'status'], name='scripts_scr_script__e03272_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'SUCCESS')), fields=('script', 'backup_date', 'backup_type'), name='unique_successful_daily_backup_per_script')],
            },
        ),
    ]
