# Generated by Django 6.1.1 on 2026-10-10 09:05

import uuid
from django.conf import settings
from django.db import migrations, models


def populate_scene_uuids(apps, schema_editor):
    """
    Populate unique UUIDs for any existing Scene records using Django historical models.
    Guarantees that pre-existing rows do not share a static default UUID value.
    """
    Scene = apps.get_model('scripts', 'Scene')
    for scene in Scene.objects.filter(scene_uuid__isnull=True).iterator():
        scene.scene_uuid = uuid.uuid4()
        scene.save(update_fields=['scene_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0009_scriptbackuplog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the scene was moved to Trash.', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether this scene is in the Trash.'),
        ),
        migrations.AddField(
            model_name='scene',
            name='original_intercut_source_uuid',
            field=models.UUIDField(blank=True, help_text='Preserved scene_uuid of intercut source scene when trashed.', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='original_order',
            field=models.PositiveIntegerField(blank=True, help_text='Preserved order position before being moved to Trash.', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='original_parent_heading',
            field=models.CharField(blank=True, default='', help_text='Preserved heading of parent scene when trashed.', max_length=255),
        ),
        migrations.AddField(
            model_name='scene',
            name='original_parent_scene_number',
            field=models.PositiveIntegerField(blank=True, help_text='Preserved scene_number of parent scene when trashed.', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='original_parent_uuid',
            field=models.UUIDField(blank=True, help_text='Preserved scene_uuid of parent scene when trashed.', null=True),
        ),
        # Step 1: Add scene_uuid as nullable so existing rows can be safely populated
        migrations.AddField(
            model_name='scene',
            name='scene_uuid',
            field=models.UUIDField(blank=True, editable=False, help_text='Persistent, immutable UUID for version snapshot and identity tracking.', null=True),
        ),
        # Step 2: Populate distinct uuid.uuid4() per existing row
        migrations.RunPython(
            populate_scene_uuids,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 3: Enforce null=False, db_index=True, default=uuid.uuid4
        migrations.AlterField(
            model_name='scene',
            name='scene_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Persistent, immutable UUID for version snapshot and identity tracking.'),
        ),
        migrations.AddField(
            model_name='script',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the screenplay was moved to Trash.', null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether this screenplay is in the Trash.'),
        ),
        migrations.AddIndex(
            model_name='scene',
            index=models.Index(fields=['script', 'is_deleted', 'order'], name='scripts_sce_script__05cdf5_idx'),
        ),
        migrations.AddIndex(
            model_name='scene',
            index=models.Index(fields=['is_deleted', 'deleted_at'], name='scripts_sce_is_dele_c7fdd3_idx'),
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['user', 'is_deleted', '-updated_at'], name='scripts_scr_user_id_80fa45_idx'),
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['is_deleted', 'deleted_at'], name='scripts_scr_is_dele_529749_idx'),
        ),
    ]
