import io
import os
import re
import logging
from datetime import date, datetime
from pathlib import Path
from typing import Optional, Dict, Any, List

from django.conf import settings
from django.core.mail import EmailMessage
from django.utils import timezone

from scripts.models import Script, ScriptBackupLog
from scripts.services.pdf_export import generate_screenplay_pdf
from scripts.services.gdrive_backup_service import save_local_backup

logger = logging.getLogger(__name__)


class EmailBackupError(Exception):
    """Base exception for screenplay email backup operations."""
    pass


class EmailConfigError(EmailBackupError):
    """Raised when email configuration or target recipient is missing/invalid."""
    pass


def resolve_script_owner_email(script: Script) -> str:
    """
    Dynamically resolves the script owner's email address from the Django auth User relationship.
    Authoritative source: script.user.email.
    Raises EmailConfigError if the script has no owner user or if user.email is blank.
    """
    user = getattr(script, 'user', None)
    if not user:
        raise EmailConfigError(f"Script '{script.title}' (ID: {script.id}) has no associated owner user.")

    owner_email = (user.email or '').strip()
    if not owner_email:
        username = getattr(user, 'username', f'User_{user.id}')
        raise EmailConfigError(
            f"Script owner '{username}' (User ID: {user.id}) does not have a configured email address."
        )
    return owner_email


def sanitize_filename_component(name: str) -> str:
    """
    Sanitizes script title for safe inclusion in filenames.
    Preserves Unicode characters and replaces unsafe filename characters with underscores.
    """
    cleaned = re.sub(r'[\/\\:*?"<>|]+', '_', name.strip())
    cleaned = re.sub(r'\s+', '_', cleaned)
    return cleaned.strip('._') or 'Screenplay'


def generate_backup_filename(script: Script, backup_date: date) -> str:
    """
    Produces standard backup filename: KadhaScript_<script-name>_<YYYY-MM-DD>.pdf
    """
    sanitized_title = sanitize_filename_component(script.title)
    date_str = backup_date.strftime('%Y-%m-%d')
    return f"KadhaScript_{sanitized_title}_{date_str}.pdf"



def build_backup_email_message(
    script: Script,
    backup_date: date,
    recipient_email: str,
    pdf_bytes: bytes,
    filename: str
) -> EmailMessage:
    """
    Constructs the Django EmailMessage containing metadata and PDF attachment.
    """
    date_str = backup_date.strftime('%Y-%m-%d')
    title_page = getattr(script, 'title_page', None)
    effective_author = title_page.get_effective_author() if title_page else (
        script.author_name or (script.user.profile.pen_name if hasattr(script.user, 'profile') else (script.user.get_full_name() or script.user.username))
    )

    from_email = (
        getattr(settings, 'DEFAULT_FROM_EMAIL', None)
        or getattr(settings, 'EMAIL_HOST_USER', None)
        or 'KadhaScript <noreply@kadhascript.com>'
    )
    subject = f"[KadhaScript] Daily Screenplay Backup - {script.title} ({date_str})"

    now_formatted = timezone.now().strftime('%Y-%m-%d %H:%M:%S %Z')

    body = f"""KadhaScript Screenplay Management Platform
==================================================
Daily Automated Screenplay Backup

Backup Date:      {date_str}
Script Title:     {script.title}
Author / Pen:     {effective_author}
Genre / Format:   {script.genre} / {script.script_type}
Language:         {script.language}
Estimated Pages:  {script.estimated_pages}
Scene Count:      {script.scene_count}

This is an automated daily backup generated by KadhaScript.
Please find the attached PDF screenplay document: {filename} ({len(pdf_bytes):,} bytes).

--------------------------------------------------
Generated at: {now_formatted}
Platform:     KadhaScript Production Management
"""

    email = EmailMessage(
        subject=subject,
        body=body,
        from_email=from_email,
        to=[recipient_email]
    )
    email.attach(filename, pdf_bytes, 'application/pdf')
    return email


def send_daily_script_backup(
    script: Script,
    backup_date: Optional[date] = None,
    recipient_email: Optional[str] = None,
    force: bool = False
) -> Dict[str, Any]:
    """
    Executes a single daily PDF backup and email delivery for the specified Script.
    Includes duplicate protection, audit logging in ScriptBackupLog, and failure resilience.
    """
    if backup_date is None:
        backup_date = timezone.localdate()

    date_str = backup_date.strftime('%Y-%m-%d')
    filename = generate_backup_filename(script, backup_date)

    # 1. Resolve and validate recipient email
    try:
        if not recipient_email:
            recipient_email = resolve_script_owner_email(script)
    except EmailConfigError as cfg_err:
        err_msg = str(cfg_err)
        logger.error("Daily backup failed for script '%s' (ID: %d): %s", script.title, script.id, err_msg)
        # Record failure log
        ScriptBackupLog.objects.update_or_create(
            script=script,
            backup_date=backup_date,
            backup_type='EMAIL',
            defaults={
                'status': 'FAILED',
                'recipient_email': '',
                'filename': filename,
                'file_size': 0,
                'error_message': err_msg
            }
        )
        return {
            'success': False,
            'skipped': False,
            'script_id': script.id,
            'script_title': script.title,
            'filename': filename,
            'date': date_str,
            'recipient': '',
            'pdf_size': 0,
            'local_path': None,
            'error': err_msg
        }

    # 2. Duplicate Protection Check
    if not force:
        existing_log = ScriptBackupLog.objects.filter(
            script=script,
            backup_date=backup_date,
            backup_type='EMAIL',
            status='SUCCESS'
        ).first()

        if existing_log:
            logger.info(
                "Duplicate protection: Daily backup for script '%s' (ID: %d) on %s was already sent to %s. Skipping.",
                script.title, script.id, date_str, existing_log.recipient_email
            )
            return {
                'success': True,
                'skipped': True,
                'reason': f"Backup already sent on {date_str} to {existing_log.recipient_email}",
                'script_id': script.id,
                'script_title': script.title,
                'filename': existing_log.filename or filename,
                'date': date_str,
                'recipient': existing_log.recipient_email,
                'pdf_size': existing_log.file_size,
                'local_path': None,
                'error': None
            }

    logger.info("Starting daily email backup for script '%s' (ID: %d) on %s -> %s", script.title, script.id, date_str, recipient_email)

    # 3. Generate PDF via existing screenplay export logic
    pdf_bytes = b''
    try:
        pdf_bytes = generate_screenplay_pdf(script, include_notes=False)
        logger.info("Generated PDF for '%s' (%d bytes)", script.title, len(pdf_bytes))
    except Exception as pdf_err:
        err_msg = f"Failed to generate screenplay PDF: {str(pdf_err)}"
        logger.error("PDF generation error for script '%s' (ID: %d): %s", script.title, script.id, err_msg, exc_info=True)
        ScriptBackupLog.objects.update_or_create(
            script=script,
            backup_date=backup_date,
            backup_type='EMAIL',
            defaults={
                'status': 'FAILED',
                'recipient_email': recipient_email,
                'filename': filename,
                'file_size': 0,
                'error_message': err_msg
            }
        )
        return {
            'success': False,
            'skipped': False,
            'script_id': script.id,
            'script_title': script.title,
            'filename': filename,
            'date': date_str,
            'recipient': recipient_email,
            'pdf_size': 0,
            'local_path': None,
            'error': err_msg
        }

    # 4. Save local fallback copy in media/backups/
    local_path = None
    try:
        local_path = save_local_backup(pdf_bytes, filename)
    except Exception as save_err:
        logger.warning("Could not save local copy of backup: %s", str(save_err))

    # 5. Construct and send Email via Django framework
    try:
        email_msg = build_backup_email_message(
            script=script,
            backup_date=backup_date,
            recipient_email=recipient_email,
            pdf_bytes=pdf_bytes,
            filename=filename
        )
        email_msg.send(fail_silently=False)
        logger.info("Daily backup email successfully delivered to %s for script '%s' (%s)", recipient_email, script.title, filename)

        # 6. Record successful backup in audit log
        ScriptBackupLog.objects.update_or_create(
            script=script,
            backup_date=backup_date,
            backup_type='EMAIL',
            defaults={
                'status': 'SUCCESS',
                'recipient_email': recipient_email,
                'filename': filename,
                'file_size': len(pdf_bytes),
                'error_message': ''
            }
        )

        return {
            'success': True,
            'skipped': False,
            'script_id': script.id,
            'script_title': script.title,
            'filename': filename,
            'date': date_str,
            'recipient': recipient_email,
            'pdf_size': len(pdf_bytes),
            'local_path': local_path,
            'error': None
        }

    except Exception as mail_err:
        err_msg = f"Email delivery failed: {str(mail_err)}"
        # Log without exposing SMTP passwords or secrets
        logger.error("Failed to send backup email to %s for script '%s': %s", recipient_email, script.title, str(mail_err), exc_info=True)
        ScriptBackupLog.objects.update_or_create(
            script=script,
            backup_date=backup_date,
            backup_type='EMAIL',
            defaults={
                'status': 'FAILED',
                'recipient_email': recipient_email,
                'filename': filename,
                'file_size': len(pdf_bytes),
                'error_message': err_msg
            }
        )
        return {
            'success': False,
            'skipped': False,
            'script_id': script.id,
            'script_title': script.title,
            'filename': filename,
            'date': date_str,
            'recipient': recipient_email,
            'pdf_size': len(pdf_bytes),
            'local_path': local_path,
            'error': err_msg
        }



def run_daily_email_backup(
    script_id: Optional[int] = None,
    backup_date: Optional[date] = None,
    recipient_email: Optional[str] = None,
    force: bool = False
) -> Dict[str, Any]:
    """
    Orchestrates daily backup email execution across target scripts.
    If script_id is given, processes that script.
    Otherwise, iterates over all scripts in the system to ensure comprehensive backup.
    """
    if backup_date is None:
        backup_date = timezone.localdate()

    date_str = backup_date.strftime('%Y-%m-%d')
    logger.info("==================================================")
    logger.info("KadhaScript Daily PDF Email Backup started for date: %s", date_str)

    if script_id is not None:
        try:
            target_script = Script.objects.get(id=script_id)
        except Script.DoesNotExist:
            err = f"Script with ID {script_id} does not exist."
            logger.error(err)
            return {
                'success': False,
                'total_scripts': 0,
                'successful_count': 0,
                'skipped_count': 0,
                'failed_count': 1,
                'results': [{
                    'success': False,
                    'skipped': False,
                    'script_id': script_id,
                    'script_title': 'Unknown',
                    'filename': '',
                    'date': date_str,
                    'recipient': recipient_email or '',
                    'pdf_size': 0,
                    'local_path': None,
                    'error': err
                }]
            }

        if target_script.is_deleted:
            err = f"Cannot back up trashed screenplay '{target_script.title}' (ID: {target_script.id})."
            logger.error(err)
            return {
                'success': False,
                'total_scripts': 0,
                'successful_count': 0,
                'skipped_count': 0,
                'failed_count': 1,
                'results': [{
                    'success': False,
                    'skipped': False,
                    'script_id': target_script.id,
                    'script_title': target_script.title,
                    'filename': '',
                    'date': date_str,
                    'recipient': recipient_email or '',
                    'pdf_size': 0,
                    'local_path': None,
                    'error': err
                }]
            }

        target_scripts = [target_script]
    else:
        target_scripts = list(Script.objects.filter(is_deleted=False).order_by('-updated_at'))
        if not target_scripts:
            msg = "No active scripts found in the database to back up."
            logger.warning(msg)
            return {
                'success': True,
                'total_scripts': 0,
                'successful_count': 0,
                'skipped_count': 0,
                'failed_count': 0,
                'results': [],
                'message': msg
            }

    results = []
    successful_count = 0
    skipped_count = 0
    failed_count = 0

    for sc in target_scripts:
        res = send_daily_script_backup(
            script=sc,
            backup_date=backup_date,
            recipient_email=recipient_email,
            force=force
        )
        results.append(res)
        if res['success']:
            if res.get('skipped'):
                skipped_count += 1
            else:
                successful_count += 1
        else:
            failed_count += 1

    overall_success = (failed_count == 0)
    logger.info(
        "KadhaScript Daily Email Backup finished: %d processed (%d sent, %d skipped, %d failed).",
        len(target_scripts), successful_count, skipped_count, failed_count
    )
    logger.info("==================================================")

    return {
        'success': overall_success,
        'total_scripts': len(target_scripts),
        'successful_count': successful_count,
        'skipped_count': skipped_count,
        'failed_count': failed_count,
        'results': results
    }
